### ISSUE TITLE
Module not found: pandas error 

### ISSUE THREAD

**Issue by anti-infective** [wshropshire/convict#2]
Hi, 
I have pandas installed but have been getting this error while trying to run convict. 

line 6, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

**Comment by wshropshire** [comment]
Hello, 

How do you have your Convict environment set up? I highly recommend creating a module file or conda environment to ensure that all dependencies are in a contained environment and that pathways are recognized for in this case your version of python you are executing for convict.py.

**Comment by wshropshire** [comment]
Please let me know if you have any other questions regarding setting up conda environments. For the time being, I'm closing this issue.
